[project]

name = "gitcommit-cli"
version = "0.10"
description = "Auto-Generate git commit messages via AI(ChatGPT) or Hueristics"
authors = [{name = "Nirvaan", email = "nirvaan@gmail.com"}]

[project.dependencies]

click = ">=8.1.7"
gitpython = ">=3.1.34"
openai = {version = ">=0.27", optional = true}
tree_sitter = {extras = ["python"], optional = true}

[project.optional-dependencies]

all = ["openai", "tree_sitter"]

[project.scripts]

gitcommit-cli = "gitcommit_cli.cli:main"